### PR TITLE
Add support for both IPv6 and IPv4 in client generated addresses

### PR DESCRIPTION
**Pull request by xeptore**
First of all, thank you for the useful handy application you made! It's really making things easier to manage.

Regarding this PR, I had a look through the previous (closed) issues for supporting IPv6 addresses both for the client and the server, and I found #3, and #54. Both of them are working, but the only thing that is currently missing is generating client `Address` from the server `Address` when server has both IPv6, and IPv4 addresses specified (in a comma-separated format as in the specification). Currently, in this case, when a user clicks on the `Generate from Server` button when adding a new client peer, the application fills the input with the first address from the server `Address` config property, either it'd be IPv4, or IPv6. For example, if the server has been configured with the `Address = 10.1.1.1/24, fda8:b84b:f7cf:14c0::/64`, clicking the button, assuming it's the first client, fills the client's `Address` input with only the value of `10.1.1.1`, where it should also respect the specified IPv6 address of the server too. Also, if the server is configured with `Address = fda8:b84b:f7cf:14c0::/64, 10.1.1.1/24`, clicking the button will only respect the IPv6 address of the server as it's the first value. This PR fixes this issue, and adds support for considering both IPv6, and IPv4 address, if specified, and generates client address considering both of them.

I tested the application after modification manually through the GUI in the following scenarios:
- When only IPv4 address of the server is set (for backward compatibility)
- When only IPv6 address of the server is set (for backward compatibility)
- When both IPv4, and IPv6 addresses of the server are set (IPv4 as the first value, and IPv6 as the second value)
- When both IPv4, and IPv6 addresses of the server are set (IPv6 as the first value, and IPv4 as the second value)

Cheers

### CODE REVIEW

**Comment by micahmo** [comment]
Hey @xeptore,

Thank you so much for catching this particular scenario, and thank you even more for taking the time to impement it. I just created a new release branch called [`release/v2.0.4`](https://github.com/micahmo/WgServerforWindows/tree/release/v2.0.4). Can you please target your PR to that branch?

Now for the changes... everything you have is good, and the scenarios you mentioned work as expected with your changes. However, there are a couple more scenarios to consider.

1. I discovered that the Server Address validation isn't quite right. It only validates the first address in the list. Therefore you could have `10.1.1.1/24, asd` and it would pass. Then, with your changes, the second generated Client Address would be bad. This not a problem you introduced, but would you consider fixing it alongside your changes? I only suggest that because your code (understandably) assumes that the server addresses are valid when it calls `IPNetwork.Parse` instead of something like `TryParse`.

2. There is an existing feature that has been lost with your changes. If the Client Address is already in the Server Address's range, it shouldn't get regenerated. Let's say my server address is `10.1.1.1/24` and my client address is `10.1.1.5`. Pressing Generate from Server should be a no-op. With your changes, it reverts the Client Address down to `10.1.1.2`. This becomes a bit tricker to do when there are multiple server ranges, but I think it would be nice to preserve if possible. You could do something like this:
    ```
    for each server address
      for each client address
        if the client address is in range
          add it to the new client addresses
          remove the server address range from consideration
    perform the remainder of your logic using unmatched server ranges
    ```

What do you think?

**Comment by xeptore** [comment]
Hey @micahmo,
Thank you for the review. Sure, I'll rebase from that branch. Regarding the possible scenarios you mentioned:

1. I agree that there are some cases that this function should handle at some point, for example, when there's no more IP left in the specified subnet, and I will need help finding a way to show an error dialogue for this case to the end user in GUI as I'm not familiar enough with Windows Forms and related stuff. However, I see this particular case that you mentioned as a special case of a more generalized application design decision, i.e., whether we can _trust_ what's already set for the server's address or not. To summarize, I think we can try parsing those splitted parts of server address (using `TryParse` for example as you mentioned), and fail with some kind of an exception if any of them are invalid. I can add the validation logic, but I'll need an example or something for failing with errors and showing an error dialogue to end-user.
2. I think this one is a more UX-oriented question. I, as an end user, personally expect the _Generate from Server_ button to actually **generate** the IP addresses. If I already filled a client address with some custom value manually, it's not reasonable to click that button anymore as I know what I'm doing, which is, _"I need this one to have this IPv6 and IPv4 addresses that I'm setting"_ for example. The button exists to make this address generation part easier for users who don't actually care what are the values, and just need something that works (unless no more addresses left in the subnet of course).

**Comment by micahmo** [comment]
Thanks for the response. Let's nail these things down before proceeding.

> I'll rebase from that branch

No need to rebase. There are no new commits in the release branch, so just re-target your PR.

1. > I see this particular case that you mentioned as a special case of a more generalized application design decision, i.e., whether we can trust what's already set for the server's address or not.

    We can trust it if it's validated properly. The problem I found is that the Server Validation doesn't handle multiple ranges. The code can be found [here](https://github.com/micahmo/WgServerforWindows/blob/1dcfbd0d9cc4903868608937960cfcaa4ef08881/WgServerforWindows/Models/ServerConfiguration.cs#L33-L57). It just needs to be extended to do the splitting and call `TryParse` on each item, rather than the whole value. Then we can trust the value downstream. If the prerequisite value is invalid, you're not even allowed to generate the Client Address (you can test this by putting a single bad Server Address). No need to invent new validation or show any dialogs. However, I can tackle this if needed.

2. I totally see where you're coming from, but I also see value in the way it works now. I think of the button as more of a "check and update if needed", which is a great way to ensure that all of your clients are valid without breaking any. If the current address is already valid, why change it? If you want to think of it another way, the button "generates" the address that you already have. There's no promise that it's the first available address in the subnet. To use your own words, "The button exists to make this address generation part easier for users who don't actually care what are the values, and just need something that works", and I totally agree!

**Comment by xeptore** [comment]
> just re-target your PR.

Done.

1. Now I understand your concern as I haven't checked the server address validation logic. I'll update the PR to make server address validation logic consider multiple address ranges (using `TryParse`).
2. I'll include this logic in this PR as well.

I'm going to mark the PR as draft for now, and will let you know once it's ready and tested.

Cheers

**Comment by xeptore** [comment]
Hey @micahmo,

I updated the PR, and included more strict validations on both server and clients address inputs. Also, I fixed the "Generate from Server" button functionality, and it now doesn't overwrite the valid existing IP address. However, while I was testing different scenarios, I faced a weird exception being thrown, but because I'm not a .NET developer, I was unable to find out why is that happening. Here's the steps to reproduce it:

1. Run the application in debug mode in Visual Studio
2. Create a sample server configuration with both IPv6, and IPv4 addresses set. Then save it.
3. Open up client configuration window, and create a new empty form for a new client config
4. Start typing anything invalid in the `Address` field of the form, e.g., `w`.
5. You'll see an `IndexOutOfRange` exception being thrown in Visual Studio in [this line](https://github.com/xeptore/WgServerforWindows/blob/main/WgServerforWindows/Models/ClientConfiguration.cs#L107).

It's really weird for me is that the function signature is `Try*`, and I expect it not to fail/throw an exception on invalid inputs. I spent about 2 hours on it, but I couldn't find out what's wrong. Maybe something for you to try while reviewing and testing.

Cheers

**Comment by micahmo** [comment]
Hey @xeptore,

Thanks again so much for spending your time on this. I'm impressed by what you've done as a non-.NET developer!

1. Currently the code is unable to build due to a missing method `AsIPNetwork`. I'm not sure if that's something you created and forgot to commit, or if it's from a package that didn't get referenced, or something else.
2. I can't test the changes (or the weird exception) as a result.
3. However, my main concern (although I can't prove it without building/testing) is that your code (both Server Address validation and Client Address generation) will only support one IPv4 and one IPv6 network. Correct me if I'm wrong, but I believe WireGuard would allow multiple addresses in the same range (at least it doesn't complain if I try!).
4. The changes _seem_ overkill (although you may be covering more scenarios / edge cases than I had originally suggested).

I really liked what you did in e483c48926e6fe0f5f7f46d4bb7651264517751a, and I didn't think we needed to add much more to finish the feature. So I cherry picked that commit and added a few more changes to address my original two points. Would you be willing to take a look at this branch and see what you think? Maybe your changes are more comprehensive and now I'm the one missing something!

**Branch**: [feature/multiple-client-addresses](https://github.com/micahmo/WgServerforWindows/tree/feature/multiple-client-addresses)
* [Changes compare to `main`](https://github.com/micahmo/WgServerforWindows/compare/main...feature/multiple-client-addresses)
* [Just my changes on top of yours](https://github.com/micahmo/WgServerforWindows/commit/b895c5dd1b3a67100ab39ce22ec27c4ada109f16)

**Tests**
Server Address | Starting Client Address | Result of Generate
-- | -- | --
  |   | N/A - Server Validation Error
asd |   | N/A - Server Validation Error
10.1.1.1/24 |   | 10.1.1.2
fda8:b84b:f7cf:14c0::/64 |   | fda8:b84b:f7cf:14c0::2
10.1.1.1/24, asd |   | N/A - Server Validation Error
fda8:b84b:f7cf:14c0::/64, asd |   | N/A - Server Validation Error
10.1.1.1/24, 10.2.1.1/24 |   | 10.1.1.2, 10.2.1.2
10.1.1.1/24, fda8:b84b:f7cf:14c0::/64 |   | 10.1.1.2, fda8:b84b:f7cf:14c0::2
fda8:b84b:f7cf:14c0::/64, 10.1.1.1/24 |   | fda8:b84b:f7cf:14c0::2, 10.1.1.2
10.1.1.1/24 | 10.1.1.3 | 10.1.1.3
fda8:b84b:f7cf:14c0::/64 | fda8:b84b:f7cf:14c0::3 | fda8:b84b:f7cf:14c0::3
10.1.1.1/24, 10.2.1.1/24 | 10.1.1.3 | 10.1.1.3, 10.2.1.2
10.1.1.1/24, fda8:b84b:f7cf:14c0::/64 | 10.1.1.3, 10.2.1.2 | 10.1.1.3, fda8:b84b:f7cf:14c0::2
fda8:b84b:f7cf:14c0::/64, 10.1.1.1/24 | fda8:b84b:f7cf:14c0::3, 10.2.1.2 | fda8:b84b:f7cf:14c0::3, 10.1.1.2
10.1.1.1/24, 10.2.1.1/24 | 10.1.1.3, 10.3.1.2 | 10.1.1.3, 10.2.1.2

> P.S. I hope this is not too heavy-handed. I'm no expert in managing open source, and I'm trying to balance your awesome contribution with the goals of the project! 😊

**Comment by xeptore** [comment]
@micahmo,
1. Yes, I upgraded https://github.com/lduchosal/ipnetwork to its latest version, but forgot to include it in the commit.
2. As above
3. Yes, I personally always use single IP for peers in the Wireguard config, and I haven't even tried using an address subnet to see whether it works, or what would be its use case. In summary, yes, this was my assumption in both IP address generation, and validation logics.
4. Yup, I made validation logic for both server, and clients really stricted.

Overall, I'm really open for your changes, and I see my changes as just an starting point for fixing an issue, and adding IPv6 support. So, feel free to change it as whatever you'd prefer and what fits the project, and more importantly, with considering backward compatibility.

**Comment by micahmo** [comment]
Thanks for the excellent discourse! I have opened PR #68 from my branch, and I would appreciate your review on it. I believe this satisfies your original request and my followup comments. You should also get credit as a contributor due to the cherry picked commit. Please feel free to keep your fork up, as I'd be happy to incorporate any additional changes in the future that cover scenarios I missed.

---

> I personally always use single IP for peers in the Wireguard config, and I haven't even tried using an address subnet to see whether it works

I didn't mean to imply a whole subnet, but rather two addresses of the same family in different subnets (like in my tests, `10.1.1.3, 10.2.1.2`). Perhaps one peer could accept connections from one address and one peer could accept another? To be honest, I've never used WireGuard to that extent.

**Comment by xeptore** [comment]
> To be honest, I've never used WireGuard to that extent.

This holds for me too. If there's a use case for this, and the effort to allow multiple addresses vs one address is worth it, then let's support that as well.

**Comment by micahmo** [comment]
> will have a look into #68 once it's ready.

It's ready. 😊

**Pull request closed without merging**
